config/routes.rb
Rails.application.routes.draw do
  
  resources:events
 
  root 'events#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/event.rb
class Event < ActiveRecord::Base
 
  validates :name, :location, presence: true
  validates :description, length: {minimum: 25}
  validates :price, numericality: {greater_than_or_equal_to: 0}
  validates :capacity, numericality: {only_integer: true, greater_than: 0}
  
  validates :image_file_name, allow_blank: true, format: {
    with: /\w+\.(gif|jpg|png)\z/i,
    message: "must reference a GIF, JPG, or PNG iamge"
  }

  def free?
    price.blank? || price.zero?
  end

  def self.upcoming
    where("starts_at >= ?", Time.now).order("starts_at")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.upcoming
  end

  def show
    @event = Event.find(params[:id])
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    @event.update(event_params)
    redirect_to @event
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.save
    redirect_to @event    
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_url
  end

  private

  def event_params
      event_params = params.require(:event).
                     permit(:name, :description, :location, :price, :starts_at, :image_file_name, :capacity)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def format_price(event)
    if event.free?
      content_tag(:strong, "Free")
    else
      number_to_currency(event.price) 
    end   
  end

  def image_for(event)
    if event.image_file_name.blank?
      image_tag 'placeholder.png'
    else
      image_tag event.image_file_name
    end
  end
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <p>
    <%= f.label :name %><br/>
    <%= f.text_field :name, autofocus: true %>
  </p>
  <p>
    <%= f.label :description %><br/>
    <%= f.text_area :description, cols: 40, rows: 7 %>
  </p>
  <p>
    <%= f.label :location %><br/>
    <%= f.text_field :location %>
  </p>
  <p>
    <%= f.label :starts_at %><br/>
    <%= f.datetime_select :starts_at %>
  </p>
  <p>
    <%= f.label :price %><br/>
    <%= f.number_field :price %>
  </p>    
  <p>
    <%= f.label :image_file_name %><br/>
    <%= f.text_field :image_file_name, size: 30, placeholder: "GIF, JPG, or PNG file name" %>
  </p> 
  <p>
    <%= f.label :capacity %><br/>
    <%= f.number_field :capacity %>
  </p> 
  <p>
    <%= f.submit %> |
    <%= link_to "Cancel", events_path %>
  </p>

<% end %>

app/views/events/edit.html.erb
<h1>Editing <%= @event.name %></h1>

<%= render 'form' %>

app/views/events/index.html.erb
<h1><%= pluralize(@events.size, "Event") %></h1>

<% @events.each do |event| %>
  <article class="event">
    <header>
      <%= image_for(event) %>
      <h2><%= link_to event.name, event %></h2>
      <h3><%= pluralize(event.capacity, 'spot') %></h3>
    </header>
    <p>
      <%= truncate(event.description, length: 35, separator: ' ') %>
    </p>  
    <table>
      <tr>
        <th>When:</th>
        <td><%= event.starts_at %></td>
      </tr>
      <tr>
        <th>Where:</th>
        <td><%= event.location %></td>
      </tr>
      <tr>
        <th>Price:</th>
        <td><%= format_price(event) %></td>
      </tr>
    </table>
  </article>
<% end %>

app/views/events/new.html.erb
<h1>Add New Event</h1>

<%= render 'form' %>

app/views/events/show.html.erb
<article>
  <header>
    <%= image_for(@event) %>
    <h1><%= @event.name %></h1>
  </header>
  <p>
    <%= @event.description %>
  </p>  
  <h3>When:</h3>
  <p>
    <%= @event.starts_at %>
  </p>
  <h3>Where:</h3>
  <p>
    <%= @event.location %>
  </p>
  <h3>Price:</h3>
  <p>
    <%= format_price(@event) %>
  </p>
  <h3>Capacity</h3>
  <p>
    <h3><%= pluralize(@event.capacity, 'spot') %></h3>
  </p>
</article>

<%= link_to("Edit", edit_event_path(@event)) %>
<%= link_to("Delete", event_path(@event), method: :delete, data: {confirm: 'Are you Sure?'}) %>

app/views/layouts/_footer.html.erb
<footer id="page-footer">
  <p>
    Copyright &copy; 2015 SCCI
  </p>
</footer>

app/views/layouts/_header.html.erb
<header id="page-header">
  <h1>Pragmatic Events</h1>
</header>

app/views/layouts/_sidebar.html.erb
<aside id="sidebar">
  <nav>
    <ul>
      <li>
        <%= link_to "All Events", events_path %>
      </li>
      <li>
        <%= link_to "Add New Event", new_event_path %>
      </li>
    </ul>
  </nav>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Events</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
            
  
  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/sidebar' %>
    
    <%= yield %>
    
    <%= render 'layouts/footer' %>

    
  </body>
</html>